# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='tutorial.proto',
  package='protobuf.socketrpc',
  serialized_pb='\n\x0etutorial.proto\x12\x12protobuf.socketrpc\"S\n\x0e\x43ommandRequest\x12,\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x1b.protobuf.socketrpc.Command\x12\x13\n\x0b\x63redentials\x18\x02 \x01(\t\"[\n\x0f\x43ommandResponse\x12.\n\x08response\x18\x01 \x02(\x0e\x32\x1c.protobuf.socketrpc.Response\x12\x18\n\x10response_message\x18\x02 \x01(\t*&\n\x07\x43ommand\x12\r\n\tPOWER_OFF\x10\x01\x12\x0c\n\x08POWER_ON\x10\x02*#\n\x08Response\x12\n\n\x06RES_OK\x10\x01\x12\x0b\n\x07RES_ERR\x10\x02\x32l\n\x0bPoshService\x12]\n\x12getCommandResponse\x12\".protobuf.socketrpc.CommandRequest\x1a#.protobuf.socketrpc.CommandResponseB\x03\x90\x01\x01')

_COMMAND = descriptor.EnumDescriptor(
  name='Command',
  full_name='protobuf.socketrpc.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='POWER_OFF', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POWER_ON', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=216,
  serialized_end=254,
)


_RESPONSE = descriptor.EnumDescriptor(
  name='Response',
  full_name='protobuf.socketrpc.Response',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RES_OK', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RES_ERR', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=256,
  serialized_end=291,
)


POWER_OFF = 1
POWER_ON = 2
RES_OK = 1
RES_ERR = 2



_COMMANDREQUEST = descriptor.Descriptor(
  name='CommandRequest',
  full_name='protobuf.socketrpc.CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='protobuf.socketrpc.CommandRequest.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='credentials', full_name='protobuf.socketrpc.CommandRequest.credentials', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=121,
)


_COMMANDRESPONSE = descriptor.Descriptor(
  name='CommandResponse',
  full_name='protobuf.socketrpc.CommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='response', full_name='protobuf.socketrpc.CommandResponse.response', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='response_message', full_name='protobuf.socketrpc.CommandResponse.response_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=214,
)

_COMMANDREQUEST.fields_by_name['command'].enum_type = _COMMAND
_COMMANDRESPONSE.fields_by_name['response'].enum_type = _RESPONSE
DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
DESCRIPTOR.message_types_by_name['CommandResponse'] = _COMMANDRESPONSE

class CommandRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.CommandRequest)

class CommandResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDRESPONSE
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.CommandResponse)


_POSHSERVICE = descriptor.ServiceDescriptor(
  name='PoshService',
  full_name='protobuf.socketrpc.PoshService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=293,
  serialized_end=401,
  methods=[
  descriptor.MethodDescriptor(
    name='getCommandResponse',
    full_name='protobuf.socketrpc.PoshService.getCommandResponse',
    index=0,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=_COMMANDRESPONSE,
    options=None,
  ),
])

class PoshService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _POSHSERVICE
class PoshService_Stub(PoshService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _POSHSERVICE

# @@protoc_insertion_point(module_scope)
